language: go

go:
    - tip

before_install:
  - pip install --user codecov

install:
    - go get github.com/layeh/gumble/gumble
    - go get github.com/layeh/gumble/gumbleffmpeg
    - go get github.com/layeh/gumble/gumbleutil
    - go get github.com/codegangsta/cli
    - go get github.com/antonholmquist/jason
    - go get gopkg.in/yaml.v2
    - go get golang.org/x/tools/cmd/cover

branches:
    only:
        - refactor

after_success:
  - codecov
